version: 2.1
orbs: # setup orbs pacages
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs: # start jobs
  build:
    docker:   # pre-configure Ubuntu image 
      - image: cimg/base:stable
    steps:    # start pipleline steps
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:  # start installation of dependencies
            name: Install Frontend
            command: |
              npm run install:frontend
      - run:
            name: Install Backend
            command: |
              npm run install:backend
      - run:    # start building and generating bundle and Archive folders
            name: Build Frontend
            command: |
              npm run build:frontend
      - run:
            name: Build Backend
            command: |
              npm run build:backend
      - run:  # start deploying to AWS cloud
            name: Deploy Frontend
            command: |
              npm run deploy:frontend
      - run:
            name: Deploy Backend
            command: |
              npm run deploy:backend
workflows:
    build-deploy-workflow:    # name of the workflow
      jobs:
        - build:    # the name of the job onstructed above
            filters:    # triger the change in master branch
              branches:
                only: 
                  - master    # name of the repo branch